UICHKIN-232: Update .gitignore file
folio-org/ui-checkin pull request #407
Opened 2021-03-10 11:55 UTC by annamelnyk

# Task
https://issues.folio.org/browse/UICHKIN-232

2021-03-10 12:10 UTC, Dmitriy-Litvinenko requested changes

2021-03-10 12:10 UTC, Dmitriy-Litvinenko commented on CHANGELOG.md
> +## [5.0.1] (IN PROGRESS)
Could you please change version to 5.1.0?

2021-03-10 12:13 UTC, Dmitriy-Litvinenko commented
@zburke @mkuklis Could you please tell us if you have any other suggestions for .gitignore?

2021-03-10 18:49 UTC, zburke commented
LGTM but I haven't thought hard about this. Other/alternative things I see in ui-users and/or ui-inventory:
```
*.idea*
junit.xml
package-lock.json
```

2021-03-10 18:49 UTC, zburke approved these changes

2021-03-10 19:23 UTC, mkuklis approved these changes

2021-03-11 07:52 UTC, Dmitriy-Litvinenko approved these changes

2021-03-11 13:56 UTC, merged