UICHKIN-310: support `circulation` `12.0`
folio-org/ui-checkin pull request #482
Opened 2021-12-08 12:03 UTC by Dmitriy-Litvinenko

## Purpose
Support okapi interfaces `circulation` `12.0`

## Approach
* Title level requests changes affect ui-requests (UIREQ) without breaking change for this module.
* The implementation of title level requests requires data migration to allow for a single queue of requests, whether item or title level (https://issues.folio.org/browse/UXPROD-3330).

## Refs
https://issues.folio.org/browse/UICHKIN-310

2021-12-08 12:22 UTC, Stanislau-Snapok approved these changes

2021-12-08 12:23 UTC, zburke requested changes
Dropping support for an interface (`circulation` `9.0`) is a major version change. Please update the `version` field in `package.json` and make note of what is changing in why in a noisy `CHANGELOG.md`, e.g. 

> * BREAKING: dropped support for `circulation` `9.0` because only versions >= 10 support foo frobbing, which is required by the bar-baz detector.

2021-12-08 13:49 UTC, Dmitriy-Litvinenko commented
@zburke  Could you please re-review?

2021-12-08 15:29 UTC, mkuklis approved these changes

2021-12-08 21:41 UTC, zburke approved these changes

2021-12-09 10:17 UTC, pavelspichonak approved these changes

2021-12-30 14:06 UTC, merged