CIRC-1784 added request.requestDate token
folio-org/ui-checkin pull request #587
Opened 2023-05-13 00:35 UTC by rgupta-nla

## Purpose
Update staff slips to have the request date

## Approach
add new token for request date

## Refs
https://issues.folio.org/browse/CIRC-1784

## Screenshots

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2023-05-15 06:24 UTC, artem-blazhko requested changes
Could you fix ESLint errors?
And could you add appropriate changes to CHANGELOG.md file?

2023-05-16 20:15 UTC, zburke requested changes
WRT the PR itself, not the code change: changes in the ui-checkin GitHub repo need tickets in the corresponding Jira project, UICHKIN. Please move CIRC-1784 into the correct project. As is, this ui-checkin feature will be affiliated with a mod-circulation release, which is incorrect.

2023-05-17 00:09 UTC, rgupta-nla commented
> WRT the PR itself, not the code change: changes in the ui-checkin GitHub repo need tickets in the corresponding Jira project, UICHKIN. Please move CIRC-1784 into the correct project. As is, this ui-checkin feature will be affiliated with a mod-circulation release, which is incorrect.

The code change is spread across four different repositories. 
mod-circulation
ui-checkin
ui-requests
ui-circulation

Are you suggesting I create three more UIXXX tickets?

2023-05-18 10:52 UTC, Dmitriy-Litvinenko commented on CHANGELOG.md
> +* Added requestDate token. Refs CIRC-1784.
Could you please update CHANGELOG.md how i understood we should change from  `Added requestDate token. Refs CIRC-1784.` to `*  Added requestDate token. Refs UICHKIN-384.`

2023-05-18 11:53 UTC, Dmitriy-Litvinenko approved these changes

2023-05-18 12:38 UTC, zburke approved these changes

2023-05-18 22:15 UTC, merged

2023-05-19 12:52 UTC, zburke commented
@rgupta-nla : please remember to squash when you merge in order to keep the commit history tidy. Thank you!